name: Deploy Laravel Project to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  apply_cicd_process:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y php php-cli php-mbstring php-xml php-bcmath php-curl php-mysql \
                              unzip curl apache2 mysql-server git composer

      - name: Start Services
        run: |
          sudo systemctl start mysql
          sudo systemctl enable mysql
          sudo systemctl start apache2
          sudo systemctl enable apache2

      - name: Create MySQL Database and User
        run: |
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS cicdsecondapp;"
          sudo mysql -e "CREATE USER IF NOT EXISTS 'laravel_user'@'localhost' IDENTIFIED BY 'StrongPassword123';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON cicdsecondapp.* TO 'laravel_user'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Setup Laravel Environment File
        run: |
          cp .env.example .env || true
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=cicdsecondapp/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=laravel_user/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=StrongPassword123/' .env

      - name: Install Laravel Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate App Key & Cache Config
        run: |
          php artisan config:clear
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Set Permissions
        run: |
          sudo chown -R $USER:www-data .
          sudo chmod -R 775 storage
          sudo chmod -R 775 bootstrap/cache

      - name: Restart Apache
        run: sudo systemctl restart apache2

      # Optional: Run PHP built-in server instead of Apache (dev only)
      - name: Start Laravel Dev Server
        run: nohup php artisan serve --host=0.0.0.0 --port=8000 &
