name: Implement Cicd of laravel project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  apply_cicd_process:
    runs-on: self-hosted
    steps:
      - name: Need to checkout
        uses: actions/checkout@v3
