name: Implement Cicd of laravel project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  apply_cicd_process:
    runs-on: self-hosted
    steps:
      - name: Need to checkout
        uses: actions/checkout@v3

      - name: Update & Install Required Packages
        run: |
          sudo apt update
          sudo apt install -y php php-cli php-mbstring php-xml php-bcmath php-curl php-mysql \
                              unzip curl apache2 mysql-server git composer

      - name: Start MySQL Service
        run: |
          sudo systemctl start mysql
          sudo systemctl enable mysql

      - name: Create MySQL User & DB
        run: |
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS laravel_db;"
          sudo mysql -e "CREATE USER IF NOT EXISTS 'laravel_user'@'localhost' IDENTIFIED BY 'your_secure_password';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON laravel_db.* TO 'laravel_user'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Laravel Environment Setup
        run: |
          cp .env.example .env || true
          php artisan config:clear
          php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Set Permissions
        run: |
          sudo chown -R $USER:www-data .
          sudo chmod -R 775 storage
          sudo chmod -R 775 bootstrap/cache

      - name: Start Apache Server
        run: |
          sudo systemctl restart apache2

      - name: Run Laravel Development Server (Optional if Apache is used)
        run: |
          nohup php artisan serve --host=0.0.0.0 --port=8000 &
